name: bmrl
channels:
  - defaults
dependencies:
  - python==3.8
  - pyopengl
  - pytorch
  - matplotlib
  - pandas
  - numpy
  - tqdm
  - jupyter
  - seaborn
  - scikit-learn
  - pip
  - pip:
    - gym==0.21
    - pyglet
